services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RUN_MODE=server
      - FRONTEND_ORIGIN=http://82.115.17.206:5500
    container_name: Backend
    env_file:
      - ./.env
    image: ghcr.io/rohamizadidoost/sheep-farming
    restart: unless-stopped
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "5500:5500"
    container_name: Frontend
    image: ghcr.io/rohamizadidoost/sheep-farming-front
    restart: unless-stopped
