services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV=production
    container_name: Backend
    env_file:
      - ./.env
    image: ghcr.io/rohamizadidoost/sheep-farming
    restart: unless-stopped
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: sheep
      POSTGRES_DB: sheepdb
    ports:
      - "5432:5432"
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "5500:5500"
    container_name: Frontend
    image: ghcr.io/rohamizadidoost/sheep-farming-front
    restart: unless-stopped