name: CD
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  deploy:
    runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Write env file
      run: echo "${{ secrets.ENV_FILE }}" > .env

    - name: Write FireBaseCred file
      run: echo "${{ secrets.FIRE_BASE_CRED }}" > sheep-farm-app-firebase-adminsdk-fbsvc-881b63938f.json
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT }}

    - name: Build and push Docker image
      run: |
        docker compose build
        docker compose push

    - name: Set up server
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        source: "docker-compose.yml , sheep-farm-app-firebase-adminsdk-fbsvc-881b63938f.json"
        target: "/root/Backend"

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd /root/Backend
          echo "${{ secrets.ENV_FILE }}" > .env
          chmod 644 .env
          
          docker compose down
          sleep 10
          docker compose pull 
          docker compose up -d 
